[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.11"

[features]
seeds = false
skip-lint = false
debug = true

[programs.localnet]
solana_dao_program = "SxDdnnHxfc2NmCoGrBQneWu5TmEw5qypGtoXsyQpbJZ"

[programs.devnet]
solana_dao_program = "SxDdnnHxfc2NmCoGrBQneWu5TmEw5qypGtoXsyQpbJZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/peer/.config/solana/id.json"
url = "http://localhost:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"